### ISSUE TITLE
Compiled css/js is not reflected in served desk

### ISSUE THREAD

**Issue by knubie** [urbit/tree#12]
I cloned this repo to make some changes to the css. Specifically I made the background of the nav red (as a test). I compiled the source into `main.js` and `main.css` and deployed them to my `%sandbox` desk locally as described here: https://github.com/urbit/tree#deploy to test my changes.

When navigating around static, the changes are not reflected, as seen here:
![screen1](https://cloud.githubusercontent.com/assets/431251/15808511/1e0caf08-2b47-11e6-9155-669b54587967.png)

However when navigating to `tree/main` the changes suddenly appear:
![screen2](https://cloud.githubusercontent.com/assets/431251/15808517/31173ac8-2b47-11e6-8c04-8441a0d4eafb.png)

I tried emptying cache, and 3 different browsers. I also tried serving and deploying to `%home` and witnessed the same results.

May be related to [arvo#154](https://github.com/urbit/arvo/issues/154).

**Comment by galenwp** [comment]
I updated those deploy instructions with the ?dbg.nopack query string info just a bit ago. 

Does http://localhost:8080/tree?dbg.nopack=true show your changes?

**Comment by knubie** [comment]
Indeed it does, thanks!

**Comment by galenwp** [comment]
Great! Sorry for the confusion. Does that make sense? We concatenate them for production to keep the number of requests down.

**Comment by ohAitch** [comment]
I really should figure out the pack renderers, it seems like the manual
solution is turning out too error-prone/confusing.

**Comment by galenwp** [comment]
It's a little confusing — but there wasn't an explanation in the readme until like ~2h ago.

**Comment by knubie** [comment]
@galenwp Yeah, so `~.codemirror_fonts_bootstrap_main.css` and `~.main_urb.js` are the files actually being requested (which are just `main.css` and `main.js` concatenated with other dependencies), and not the `main.css` and `main.js` that were generated with `build/watch.sh`.

Makes sense to me.

**Comment by galenwp** [comment]
Yep.  That's it.  We'll see if others get tripped up.

Look forward to the CSS fixes you come up with.  There are definitely rough spots in this thing.
