### ISSUE TITLE
Back button breaks after loading an urbit app module (talk, dojo)

### ISSUE THREAD

**Issue by knubie** [urbit/tree#14]
When clicking on an urbit app like dojo or talk from within tree, the back button breaks. The url updates but the page doesn't change.

**Comment by galenwp** [comment]
I would guess that the easiest way to reproduce this would be to just click on talk from the your-ship.urbit.org.  Is that how you found it?

**Comment by knubie** [comment]
Yeah, click on talk, then hit back, starting from the file browser (it works if going from home -> talk, then back to home). A flux error appears in the console.

**Comment by galenwp** [comment]
Sorry, I managed to hose `~talsur-todres` somehow.   Bringing up a new ship.

**Comment by knubie** [comment]
I'm wondering if this is even reproducible because I've been noticing a couple bugs pop up in talk ever since I clone and deployed tree from github. So now I'm thinking this might just be another bug that's specific to my urbit.

**Comment by galenwp** [comment]
I think those `:talk` bugs are unrelated.  Sorry, I got sucked into other stuff.  Can test on my new `~barred-tidset`.

**Comment by galenwp** [comment]
Okay — triggered it.  Seems like there's another navigation bug when the comments component is present on the page too, but I didn't fully track it down.

**Comment by knubie** [comment]
Ah yeah, I noticed that too with the comment module but didn't look much into it. 1bbfcee seems to fix that as well, for me, at least.

**Comment by knubie** [comment]
Slightly off-topic, would it make sense to create a separate station for tree? I've been tinkering with it a bit and might be nice to have a place to chat about it in `:talk`.

**Comment by galenwp** [comment]
The first non `/urbit-meta` station!  It's a big move.  Maybe you're right.  We're working to get comments working better — which should allow for comfortable asynchronous communication.  Discussion like this fits better in a comment model, no?

**Comment by knubie** [comment]
Oh, I didn't even think about comments! I forgot that you can `;join` them like stations. Yeah that would be nice, I'll follow your lead either way.
