### ISSUE TITLE
Uncaught TypeError: "urb.init is not a function" on pageload

### ISSUE THREAD

**Issue by Fang-** [urbit/tree#18]
When loading up an Urbit web page (of any planet) the following error appears in the browser's console:

```
tree-urb.js:1712 – Uncaught TypeError: urb.init is not a function
```

A nearly identical error gets thrown when clicking "Save" after editing name and location on my own planet's homepage (and the changes don't get saved):

```
react.min.js:14 – Uncaught TypeError: urb.init is not a function
```

Full stack traces from both error messages can be found [here](http://pastebin.com/JkjDybrK).

From the urbit-meta chat:

```
~fyr= i'm guessing the problem is deployment state
~fyr= where the new tree.js was pushed but the new urb.js wasn't
```

**Comment by galenwp** [comment]
Since that `urbit/arvo` PR was merged, can we close this @ohAitch?

**Comment by Fang-** [comment]
Ping, this has been fixed and can be closed.
