### ISSUE TITLE
Nav links don't appear after logging in

### ISSUE THREAD

**Issue by galenwp** [urbit/tree#22]
I haven't reproduced this — but apparently after logging in the nav links aren't displayed.  After editing the plan and saving, they are.

![image](https://cloud.githubusercontent.com/assets/1467211/16678913/aa8df29c-4498-11e6-937e-d6720bc89f85.png)

**Comment by redhookecho** [comment]
I have this problem.  Ubuntu 16.04, Firefox for Ubuntu 47.0

When I first open local host I am presented with the above page, but no "Edit" link.
After I log in, I am presented with the above page.
After clicking on the "Edit" link and then "Save" without making any changes to the fields, the "Talk" Dojo" and "Static" links will appear.

**Comment by galenwp** [comment]
@ohAitch did that fix go out?
