### ISSUE TITLE
Comments reverse order

### ISSUE THREAD

**Issue by galenwp** [urbit/tree#26]
There should be an option like `comments-order` that can flip the order of comments and put the comment box at the bottom.

**Comment by ohAitch** [comment]
I'd just go for "comments: reverse", I'm kind of wary of growing a
half-dozen yaml fields that boil down to "type: forum-post".

**Comment by galenwp** [comment]
Works for me, although I wish there were clear inverses.  Does `comments:forward` mean the same thing as `comments:true`?

**Comment by ohAitch** [comment]
I'd do something like "show", "show reverse" eventually, if we e.g. add an
"only postable by logged-in urbits" option.

**Comment by galenwp** [comment]
Well there's never going to be a 'hide', right?  That is, the existence of the `comments` attribute implies that we want to show comments — and the body tells us what to do with them?

**Comment by ohAitch** [comment]
I'm mentally slotting in "hide" for the unnamed default, whose value rn is
effectively "". But sure it could be e.g. "full", contrast "read". My point
is that three options is probably too early to make it rigorous.

(For now, I'm just going to pretend "true" stands for "in true order", as
opposed to "reverse" which is chrono order)
