### ISSUE TITLE
How to get started with the ES6 Dev branch.

### ISSUE THREAD

**Issue by h-cow** [urbit/tree#31]
I'm not sure how to get started with the es6 dev branch. Currently the master branch is in Coffee.

- What is the current development branch for Tree/Talk that uses es6?
- What Arvo branch do I need
- Is there a certain urbit.pill I need

Is there anymore pieces of the puzzle I need in order to make a fake ~zod so I can help dev on Tree?

**Comment by galenwp** [comment]
@ohAitch and I have been working on separate development branches.  @ohAitch worked on the `arvo` changes, and I was purely making the ES6 / Redux conversion.  I believe @ohAitch was a few commits ahead of me with his own changes, but I'll tell you where I left off.   It shouldn't be a problem to pick up from my last `es6` commits and catch up to where @ohAitch is.

You should be able to take https://github.com/galenwp/tree/tree/es6 and boot it on a fake zod using my https://github.com/galenwp/arvo/tree/es6 branch.  (There are only two minor changes to arvo there, so the pill that gets auto-downloaded is fine.  It's basically maintenance.)  

As far as Urbit is concerned, `tree` is just `/===/web/tree/main.css` and ``/===/web/tree/bundle.js`.  In your `tree` repo you'll need a `grunt.config.js` that defines `arvo` and `pier` (see usage: https://github.com/galenwp/tree/blob/es6/gruntfile.js).  This means that when you run `npm run watch-js` and `grunt watch` your `.js` will get bundled and copied into both your `arvo` repo and a running pier.  

Happy to answer any other questions.  I was in the midst of converting our components.  I have a list of what needs to be done that I should probably just turn into GH issues.  It's pretty easy to do.

**Comment by h-cow** [comment]
Thank you! This should be helpful.

**Comment by h-cow** [comment]
I'm stuck on trying to just get Urbit to mount my home folder.

Dojo ```|mount /=home=``` and ```|mount %``` are not working. The prompt will show me a ```>=``` but the folder does not mount. Other folders will mount though.

Strangely enough my normal planet will not mount either but a random comet will mount the home folder.

**Comment by galenwp** [comment]
Is it possibly a permissions problem?  What do you mean by 'other folders will mount'?  Can you `|mount /=home=/web`?

**Comment by cgyarvin** [comment]
Okay this is incredibly weird.

What platform, etc?  Can you send a console paste?

**Comment by h-cow** [comment]
```|mount /=home=/web``` correct. I forgot what you said about Urbits only concerned with the 2 files. I'll go forward with just the web folder.

What Platform?
1. Elementary OS 0.4 Loki based off of Ubuntu 16.04 (Desktop)
2. Ubuntu 16.10 (Server) fresh install just for Urbit

I also can not log onto https://my-planet.urbit.org anymore and I don't know if thats related to not being able to mount.

**Comment by h-cow** [comment]
Victory! now I can play. Thanks for the help.

**Comment by galenwp** [comment]
Sounds like you got this sorted out.  Were you ever able to log in via the web?

**Comment by h-cow** [comment]
I was not able to log on via the web. Issues that I still had when trying to work on tree included.
- not being able to log on via web
- not being able to mount home
- not able to add folders in my mounted "web" folder

I gave up when trying to fix many of these issues. Tree without custom folders just didn't grab me as exciting.

For now I'm just going to keep my eye on this project. When it looks like I can start developing some fun services for Urbit such as a time clock, calendar or other useful things I would like to have on a personal server. Also I need to see if you can even implement such things using JavaScript

I spent many hours on Urbit already just trying to get stuff to work and I feel I need to be more productive with my free time. I can't wait for Urbit to grow a bit more. Its going to be awesome!

**Comment by galenwp** [comment]
Sorry to hear it!  But I do understand.  Urbit isn't quite ready for the kinds of applications you are describing.  The system itself is still stabilizing.  It's not impossible to build what you're describing, but you'd be starting from scratch.  But, I do agree — it will be awesome once things get more stable!

Anyway, Urbit should easily support the three things you list as not working.  I wish we could have tracked down specific reproduction cases.  I'll leave some questions here, but if you don't have time to get back into this that's totally fine.

- When you say you can't log in via the web, what exactly happens?  Does http://your-urbit.urbit.org load at all?  What about when accessed directly either via IP (if it's in the cloud) or via `localhost:8080`?
- When you try to `|mount %` you should see `your-urbit/home` get created in Unix.  That is: inside the directory where your Urbit is running you should get a `home/` folder.  When you run that command, do you just see a `>=` and see no change in Unix?  

In the case of folders this is a bug: https://github.com/urbit/urbit/issues/321.  The workaround is to `mkdir web/something && touch web/something/placeholder.txt`.  It's ugly, but it does work.
